$ANSIBLE_VAULT;1.1;AES256
30393133323335646630386434373436303830353038343938613232646663333063616534636637
3334333764633863356232616638646365313430326235640a623761616235313033373334633932
39313333363162373830666130353662376230633861373030646633366564626265643331656234
3738666137626165330a366631323165656236346665613730323932643165383635343037323330
30346462323236366636346236393237316630636633316136396538313231336562373731393631
66333962373966326430646336343539353862363135636636363765666561653333316437323032
31336162326437653535313062613034653164353666363734373436313630646138326239346434
31386338333038316131663933383636356131356137343832643334363037626662336564346162
64366131356633303266346263333564663031386131636532643537303830313964313639376437
66393733613138636434613034623062393131636264336464306236313538303365376532393133
323961393439363838313637613634316165
